on: [push, pull_request]

jobs:
  stc_rpncalc_ci_job:
    runs-on: ubuntu-latest
    name: CI build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          tags: local:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          push: false
      - name: Desktop build/check
        uses: addnab/docker-run-action@v3
        with:
          image: local:latest
          run: $GITHUB_WORKSPACE/steps/desktop_build_check.sh --rebuild
      - name: Calc build
        uses: addnab/docker-run-action@v3
        with:
          image: local:latest
          run: $GITHUB_WORKSPACE/steps/build_calc.sh
      - name: ls
        run: ls $GITHUB_WORKSPACE
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stc_rpncalc_artifacts
          path: |
            ${{ github.workspace }}/build/
            ${{ github.workspace }}/build_qt/lcov/
            ${{ github.workspace }}/build_qt/decn.c.gcov
            ${{ github.workspace }}/build_qt/Testing/
            ${{ github.workspace }}/main.hex
          if-no-files-found: error

